version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'


# ------------------------ LEFT BLOCK ------------------------ #

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    foreground = 'blue'
    template = ' '

  [[blocks.segments]]
    type = 'path'
    foreground = 'blue'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    foreground = 'white'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}magenta{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}', '{{ if gt .Ahead 0 }}green{{ end }}']
    template = '{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      branch_icon = ' '

  [[blocks.segments]]
    type = 'executiontime'
    foreground = 'yellow'
    template = '{{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'round'
      threshold = 5000


# ------------------------ RIGHT BLOCK ------------------------ #

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = "project"
    foreground = "cyan"
    template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }} {{.Version}}{{ end }}{{ end }}"

  [[blocks.segment]]
    type = "rust"
    foreground = "red"
    template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"

    [blocks.segments.properties]
      display_mode = "always"

  [[blocks.segments]]
    type = 'node'
    foreground = 'red'
    template = '  {{ .Full }}'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    foreground = 'red'
    template = '  {{ .Full }}'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = "haskell"
    foreground = "#906cff"
    template = "  {{ .Full }}"

  [[blocks.segments]]
    type = "lua"
    foreground = "blue"
    template = "  {{ .Full }}"

# ------------------------ PROMT ------------------------ #

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'
    template = '{{ .Env.JOBS }} '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '' #'❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = ' '

[secondary_prompt]
  foreground = 'green'
  background = 'transparent'
  template = ' '


[[tooltips]]
  type = 'git'
  tips = ['git']
  style = 'diamond'
  foreground = 'white'
  background = 'orange'
  leading_diamond = ''
  trailing_diamond = ''
  template = ' {{ .HEAD }} '

  [tooltips.properties]
    display_default = true
